name: Go

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build & Run Tests
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.21
      uses: actions/setup-go@v4
      with:
        go-version: ^1.21

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Building
      run: go build -v ./...

    - name: Testing
      run: go test -cover ./...
